services:
  springboard_be:
    build: .
    container_name: springboard_be
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./zap.log:/app/zap.log
      - ./configs/config.yaml:/app/configs/config.yaml
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.springboard_be-http.entrypoints=http"
      - "traefik.http.routers.springboard_be-http.middlewares=redir-https"
      - "traefik.http.routers.springboard_be.rule=Host(`springboard.${DOMAIN}`)"
      - "traefik.http.routers.springboard_be-http.service=noop@internal"
      - "traefik.http.routers.springboard_be-https.entrypoints=https"
      - "traefik.http.routers.springboard_be-https.tls=true"
      - "traefik.http.routers.springboard_be-https.middlewares=gzip"
      - "traefik.http.routers.springboard_be-https.rule=Host(`springboard.${DOMAIN}`)"
      - "traefik.http.routers.springboard_be-https.service=springboard_be"
      - "traefik.http.services.springboard_be.loadbalancer.server.scheme=http"
      - "traefik.http.services.springboard_be.loadbalancer.server.port=8000"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env 
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}  
    volumes:
      - type: bind
        source: /home/ubuntu/redis/data
        target: /data
    networks:
      - app_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: springboard
      TZ: Asia/Shanghai
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf:/etc/mysql/conf.d
      - /home/ubuntu/mysql/logs:/var/log/mysql
    networks:
      - app_network
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--host-cache-size=0",  
    ]


networks:
  app_network:
    driver: bridge