services:
  springbroad_be:
    build: .
    container_name: springbroad_be
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./zap.log:/app/zap.log
      - ./configs/config.yaml:/app/configs/config.yaml
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env 
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}  
    volumes:
      - type: bind
        source: /home/ubuntu/redis/data
        target: /data
    networks:
      - app_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: springbroad
      TZ: Asia/Shanghai
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf:/etc/mysql/conf.d
      - /home/ubuntu/mysql/logs:/var/log/mysql
    networks:
      - app_network
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--host-cache-size=0",  
    ]


networks:
  app_network:
    driver: bridge