name: Deploy on Tag with Docker Compose

on:
  push:
    tags:
      - 'v*' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}

    - name: Upload files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/springboard"

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        port: 22
        key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
        script: |
          cd /home/ubuntu/springboard/server
          sudo docker-compose down
          sudo docker-compose up -d --build
